### Constructores de matrices

NumPy provee diversas funciones para crear matrices , algunas de las cuales ya vimos cuando estudiamos vectores , la diferencia consiste en que ahora ya no usamos un número para indicar el tamaño de un vector, si no una **tupla** de 2 elementos: (m,n) . Algunas de las funciones  que aplican tanto a vectores como a matrices son:

* np.array: crear una matriz a partir de una lista de listas: cada fila es una sublista
* np.zeros: crear una matriz de ceros
* np.ones: crear una matriz de unos
* np.empty: crear una matriz sin importarnos sus valores
* np.full: crear una matriz  con cierto valor
* np.copy: crea un clon o copia de cierta matriz

Algunas funciones específicas de matrices son:

* np.matrix: resultado casi identico a la función mas general np.array ,pero posee algunas propiedades adicionales específicas de listas, por ejemplo notación sencilla para inversas de matrices.
* np.eye: crear una matriz con 1s en su diagonal principal y ceros en el resto
* np.identity : crear una matriz identidad

Algunas funciones que solo aplican a vectores y no a matrices son:

* np.arange
* np.linspace

Existen otras pero estas son posiblemente las mas comunes. Puedes consultar las otras disponibles en: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

La diferencia de ambos radica en el que np.matrix define un objeto de dos dimensiones mientras que np.array si define objetos de cualquier entero como dimensión. Además los operadores y las funciones definidas sobre éstos son diferentes u operan de forma diferente, ejemplos de ésto lo podemos ver a continuación:

In [1]:
import numpy as np

In [7]:
mat_a = np.mat('4 3; 2 1')
mat_b = np.mat('1 2; 3 4')
print("mat_a")
print(mat_a)
print("mat_b")
print(mat_b)

array_a = np.array([[4, 3], [2, 1]])
array_b = np.array([[1, 2], [3, 4]])
print("array_a")
print(array_a)
print("array_b")
print(array_b)


mat_a
[[4 3]
 [2 1]]
mat_b
[[1 2]
 [3 4]]
array_a
[[4 3]
 [2 1]]
array_b
[[1 2]
 [3 4]]


Vemos que la primer diferencia es con el operador "*", ya que para np.matrix hace la multiplicación matricial mientras que np.array hace la multiplicación de Hadamard (elemento por elemento), para obtener la multiplicación matricial con np.array debemos usar la función np.dot.

In [5]:
print("mat_a*mat_b")
print(mat_a*mat_b)
print("array_a*array_b")
print(array_a*array_b)
print("np.dot(array_a,array_b)")
print(np.dot(array_a,array_b))

mat_a*mat_b
[[13 20]
 [ 5  8]]
array_a*array_b
[[4 6]
 [6 4]]
[[13 20]
 [ 5  8]]


Otra diferencia es el operador "**" ya que para np.matrix hace la multiplicación matricial de la matriz la cantidad de veces especificada mientras que para np.array otra vez hace la potencia elemento a elemento.

In [6]:
print("mat_a**2")
print(mat_a**2)
print("array_a**2")
print(array_a**2)

mat_a**2
[[22 15]
 [10  7]]
array_a**2
[[16  9]
 [ 4  1]]


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [8]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [9]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [12]:
X = np.array([
    [1,1],
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

In [13]:
HL_1 = [0.712,0.112]
HL_2 = [0.355,0.855]
HL_3 = [0.268,0.468]

OL = [0.116,0.329,0.708]

H1_W = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])
OL_W = np.array([[0.116],[0.329],[0.708]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  
print(OL)

In [15]:
def ReLu(x):
    return x

In [16]:
H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  
OL = np.matmul(H1,OL_W)
OL = ReLu(OL)  
print(OL)

[[0.81275154]
 [0.85897151]
 [0.6748703 ]
 [1.14904686]
 [1.15125178]
 [1.14187076]
 [0.72619803]
 [1.15019715]
 [1.153     ]
 [1.1500904 ]
 [1.153     ]]
